
package ballisticcalc.GUI;

import ballisticcalc.Utilities.TextFieldVerifier;
import ballisticcalc.Utilities.NumberFieldVerifier;
import ballisticcalc.models.Cartridge;
import ballisticcalc.Utilities.DBUtilities;
import javafx.scene.control.ComboBox;

import java.util.ArrayList;
import javax.swing.*;

/**
 * Dialog to add cartridge data to database
 *
 * @author RibitIII
 */
public class AddCartridgeGUI extends javax.swing.JDialog {

    private final DBUtilities db = new DBUtilities();

    private JTextField jBCTextField;
    private JTextField jBrandTextField;
    private javax.swing.JComboBox<String> jCaliberComboBox;
    private JTextField jMVTextField;
    private javax.swing.JComboBox<String> jManufacturerComboBox;
    private JTextField jWeightTextField;

    /**
     * Creates new form AddCartridge
     *
     * @param parent - the parent container
     * @param modal - The mode of jDialog
     */
    public AddCartridgeGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        
        clearForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        JPanel jPanel1 = new JPanel();

        JLabel jLabel1 = new JLabel("Manufacturer");
        JLabel jLabel2 = new JLabel("Brand Name");
        JLabel jLabel3 = new JLabel("Caliber");
        JLabel jLabel4 = new JLabel("Bullet Weight");
        JLabel jLabel5 = new JLabel("Muzzle Velocity");
        JLabel jLabel6 = new JLabel("Ballistic Coefficient");

        JButton jSaveButton = new JButton();
        JButton jButton2 = new JButton();
        JButton jCloseButton = new JButton();

        jManufacturerComboBox = new javax.swing.JComboBox<>();
        jCaliberComboBox = new javax.swing.JComboBox<>();

        jBrandTextField = new JTextField();
        jWeightTextField = new JTextField();
        jMVTextField = new JTextField();
        jBCTextField = new JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBrandTextField.setPreferredSize(new java.awt.Dimension(300, 25));

        jMVTextField.setPreferredSize(new java.awt.Dimension(59, 25));

        jBCTextField.setPreferredSize(new java.awt.Dimension(59, 25));

        jManufacturerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (jManufacturerComboBox.getSelectedIndex() == 1){
                    jComboBoxAction(evt.getSource(), "Enter New Manufacturer Name", "Add Manufacturer");
                }
            }
        });

        jCaliberComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Caliber" }));
        jCaliberComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (jCaliberComboBox.getSelectedIndex() == 1) {
                    jComboBoxAction(evt.getSource(), "Enter New Caliber", "Add Caliber");
                }
            }
        });

        jBrandTextField.setInputVerifier(new TextFieldVerifier("Brand Name"));
        jWeightTextField.setInputVerifier(new NumberFieldVerifier("Bullet Weight"));
        jMVTextField.setInputVerifier(new NumberFieldVerifier("Muzzle Velocity"));
        jBCTextField.setInputVerifier(new NumberFieldVerifier("BallisticCoefficient"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jWeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(jMVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(jBCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBrandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jManufacturerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCaliberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, jBrandTextField, jCaliberComboBox, jManufacturerComboBox);

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCaliberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jManufacturerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBrandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jWeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jMVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jBCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, jBrandTextField, jCaliberComboBox, jManufacturerComboBox);

        jSaveButton.setText("Save");
        jSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Clear Form");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearForm();
            }
        });

        jCloseButton.setText("Close");
        jCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispose();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jSaveButton)
                .addGap(41, 41, 41)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCloseButton)
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, jButton2, jCloseButton, jSaveButton);

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSaveButton)
                    .addComponent(jButton2)
                    .addComponent(jCloseButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }

    private void jSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveButtonActionPerformed
        if (jManufacturerComboBox.getSelectedIndex() < 2) {
            JOptionPane.showMessageDialog(null, "Please Select Manufacturer", "Error", JOptionPane.WARNING_MESSAGE);

        } else if (jCaliberComboBox.getSelectedIndex() < 2) {
            JOptionPane.showMessageDialog(null, "Please Select Caliber", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            saveToDatabase();
        }
    }

    private void jComboBoxAction (Object object, String message, String title) {
        if (!(object instanceof JComboBox)) {
            return;
        }

        JComboBox jComboBox = (JComboBox) object;

        String itemNew = JOptionPane.showInputDialog(
                null,
                message,
                title,
                JOptionPane.PLAIN_MESSAGE
        );

        if (itemNew != null) {
            if (itemNew.length() > 0) {
                jComboBox.addItem(itemNew);
                jComboBox.setSelectedItem(itemNew);
            } else {
                jComboBox.setSelectedIndex(0);
            }
        } else {
            jComboBox.setSelectedIndex(0);
        }
    }

    private void clearForm() {
        populateManufacturer();
        populateCaliber();
        jManufacturerComboBox.setSelectedIndex(0);
        jCaliberComboBox.setSelectedIndex(0);

        jBrandTextField.setText("");
        jWeightTextField.setText("");
        jMVTextField.setText("");
        jBCTextField.setText("");
    }

    private void populateManufacturer() {
        jManufacturerComboBox.removeAllItems();
        jManufacturerComboBox.addItem("Select Manufacturer");
        jManufacturerComboBox.addItem("Add New Manufacturer");
        ArrayList<String> manuList = db.distinctSelect("Manufacturer", "ORDER BY Manufacturer");
        manuList.stream().forEach((s) -> {
            jManufacturerComboBox.addItem(s);
        });
    }

    private void populateCaliber() {
        jCaliberComboBox.removeAllItems();
        jCaliberComboBox.addItem("Select Caliber");
        jCaliberComboBox.addItem("Add New Caliber");
        ArrayList<String> caliberList = db.distinctSelect("Caliber", "ORDER BY Caliber");
        caliberList.stream().forEach((s) -> {
            jCaliberComboBox.addItem(s);
        });
    }

    private void saveToDatabase() {
        if (!verifyFields()){
            return;
        }
        
        Cartridge cartridge = new Cartridge();

        cartridge.setManufacturer(jManufacturerComboBox.getSelectedItem().toString());
        cartridge.setCaliber(jCaliberComboBox.getSelectedItem().toString());
        cartridge.setBrandName(jBrandTextField.getText());
        cartridge.setWeight(Double.parseDouble(jWeightTextField.getText()));
        cartridge.setMuzzleVelocity(Double.parseDouble(jMVTextField.getText()));
        cartridge.setBallisticCoefficient(Double.parseDouble(jBCTextField.getText()));

        db.insert(cartridge);

        clearForm();
    }
    
    private boolean verifyFields(){

        return (jBrandTextField.getInputVerifier().shouldYieldFocus(jBrandTextField) && 
                jWeightTextField.getInputVerifier().shouldYieldFocus(jWeightTextField) &&
                jMVTextField.getInputVerifier().shouldYieldFocus(jMVTextField) &&
                jBCTextField.getInputVerifier().shouldYieldFocus(jBCTextField));
    }
}
